blueprint:
  name: Tradfri Switch to Light via zigbee2mqtt
  description: "Updated to Z2M v2. Controls a light with a given TRADFRI on/off switch. \n\nShort Button press will toggle light for both Buttons (helpfull in darkness) \n\n Mode set to restart is mandatory for stop after long press to work."
  domain: automation
  input:
    source_switch_action:
      name: Tradfri Switch
      description: The switch-action which triggers this automation.
      selector:
        device:
          entity:
            integration: mqtt 
            domain: button
          filter:
            manufacturer: IKEA
    target_light:
      name: Target Light
      description: the light you want to control.
      selector:
        target:
          entity:
            domain: light
alias: Tradfri Switch to Light via z2m-v2
description: ""
trigger:
- domain: mqtt
  trigger: device
  device_id: !input source_switch_action
  type: action
  subtype: "on"
  id: "on"  
- domain: mqtt
  trigger: device
  device_id: !input source_switch_action
  type: action
  subtype: "toggle"
  id: "on"  
- domain: mqtt
  trigger: device
  device_id: !input source_switch_action
  type: action
  subtype: "off"
  id: "off"  
- domain: mqtt
  trigger: device
  device_id: !input source_switch_action
  type: action
  subtype: "brightness_up_click"
  id: "brightness_up_click"  
- domain: mqtt
  trigger: device
  device_id: !input source_switch_action
  type: action
  subtype: "brightness_move_up"
  id: "brightness_move_up"  
- domain: mqtt
  trigger: device
  device_id: !input source_switch_action
  type: action
  subtype: "brightness_up_hold"
  id: "brightness_move_up" 
- domain: mqtt
  trigger: device
  device_id: !input source_switch_action
  type: action
  subtype: "brightness_down_click"
  id: "brightness_down_click"  
- domain: mqtt
  trigger: device
  device_id: !input source_switch_action
  type: action
  subtype: "brightness_move_down"
  id: "brightness_move_down"  
- domain: mqtt
  trigger: device
  device_id: !input source_switch_action
  type: action
  subtype: "brightness_down_hold"
  id: "brightness_move_down"  
- domain: mqtt
  trigger: device
  device_id: !input source_switch_action
  type: action
  subtype: "brightness_stop"
  id: "brightness_stop"  
- domain: mqtt
  trigger: device
  device_id: !input source_switch_action
  type: action
  subtype: "brightness_up_release"
  id: "brightness_stop"  
- domain: mqtt
  trigger: device
  device_id: !input source_switch_action
  type: action
  subtype: "brightness_down_release"
  id: "brightness_stop"  
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - "on"
        sequence:
          - service: light.toggle
            data: {}
            target: !input target_light
      - conditions:
          - condition: trigger
            id:
              - "off"
        sequence:
          - service: light.toggle
            data: {}
            target: !input target_light
      - conditions:
          - condition: trigger
            id:
              - "brightness_up_click"
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: >
                {{(state_attr(target_light, 'brightness_pct')|float * 1.4)|int }}
            target: !input target_light
      - conditions:
          - condition: trigger
            id:
              - "brightness_down_click"
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: >
                {{(state_attr(target_light, 'brightness_pct')|float * 0.71)|int }}
            target: !input target_light
      - conditions:
          - condition: trigger
            id:
              - brightness_move_up
        sequence:
          - repeat:
              sequence:
                - service: light.turn_on
                  data:
                    brightness_step_pct: 2
                    transition: 0.2
                  target: !input target_light
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 200
              count: 50
      - conditions:
          - condition: trigger
            id:
              - brightness_move_down
        sequence:
          - repeat:
              sequence:
                - service: light.turn_on
                  data:
                    transition: 0.2
                    brightness_step_pct: -2
                  target: !input target_light
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 200
              count: 50
mode: restart